USE HR

GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME LIKE '%Colour%')
BEGIN
	CREATE TABLE Colour
	(
		ColourId	int NOT NULL PRIMARY KEY identity(1,1)
		,Hex	varchar(20) NOT NULL
	)
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Colour' AND COLUMN_NAME = 'Name')
BEGIN
	ALTER TABLE Colour
	DROP COLUMN Name
END

IF EXISTS(SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[FK__Colour__Organisa__60C757A0]') AND parent_object_id = OBJECT_ID('Colour'))
BEGIN
	ALTER TABLE Colour
	DROP CONSTRAINT FK__Colour__Organisa__60C757A0
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Colour' AND COLUMN_NAME = 'OrganisationId')
BEGIN
	ALTER TABLE Colour
	DROP COLUMN OrganisationId
END

