USE [HR]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS(SELECT 1  FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'JobTitleJobGrade')
BEGIN

	CREATE TABLE [dbo].JobTitleJobGrade(
		[JobTitleJobGradeId] [int] IDENTITY(1,1) NOT NULL,		
		[JobTitleId] [int] FOREIGN KEY REFERENCES JobTitle([JobTitleId]),			
		[JobGradeId] [int] FOREIGN KEY REFERENCES JobGrade(JobGradeId),			
		[OrganisationId] [int] FOREIGN KEY REFERENCES Organisation(OrganisationId),
	 CONSTRAINT [PK_JobTitleJobGradeId] PRIMARY KEY CLUSTERED 
	(
		[JobTitleJobGradeId] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
	
END