USE [HR]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS(SELECT 1  FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'OvertimePreference')
BEGIN

	CREATE TABLE [dbo].OvertimePreference(
		[OvertimePreferenceId] [int] IDENTITY(1,1) NOT NULL,
		[Name] nvarchar(50) NOT NULL
	 CONSTRAINT [PK_OvertimePreference] PRIMARY KEY CLUSTERED 
	(
		[OvertimePreferenceId] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
	
	
	EXECUTE('INSERT INTO OvertimePreference (Name) VALUES (''Paid''), (''Lieu'')')
END