USE [HR]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS(SELECT 1  FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'JobTitleDocument')
BEGIN

	CREATE TABLE [dbo].JobTitleDocument(
		[JobTitleDocumentId] [int] IDENTITY(1,1) NOT NULL,
		[OrganisationId] [int] NOT NULL FOREIGN KEY REFERENCES Organisation(OrganisationId),
		[JobTitleId] [int] NOT NULL FOREIGN KEY REFERENCES JobTitle(JobTitleId),
		[Name] [nvarchar](255) NOT NULL
	 CONSTRAINT [PK_JobTitleDocument] PRIMARY KEY CLUSTERED 
	(
		[JobTitleDocumentId] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
	
END