USE [HR]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS(SELECT 1  FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Building' AND COLUMN_NAME = 'Name')
BEGIN
	ALTER TABLE Building
	Add Name Int
	EXECUTE('UPDATE Building SET Name = ''')
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Building' AND COLUMN_NAME = 'Address1')
BEGIN
	ALTER TABLE Building
	ALTER COLUMN Address1 NVARCHAR(100) NULL
END
