IF NOT EXISTS(SELECT 1  FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Employment' AND COLUMN_NAME = 'JobTitleId')
BEGIN
	ALTER TABLE Employment
	ADD JobTitleId INT Null	
END

IF NOT EXISTS(SELECT 1  FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Employment' AND COLUMN_NAME = 'JobGradeId')
BEGIN
	ALTER TABLE Employment
	ADD JobGradeId INT Null	
END