USE [HR]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS(SELECT 1  FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'OvertimeState')
BEGIN

	CREATE TABLE [dbo].OvertimeState(
		[OvertimeStateId] [int] IDENTITY(1,1) NOT NULL,
		[Name] nvarchar(50) NOT NULL
	 CONSTRAINT [PK_OvertimeState] PRIMARY KEY CLUSTERED 
	(
		[OvertimeStateId] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
	
	
	EXECUTE('INSERT INTO OvertimeState (Name) VALUES (''Requested''), (''Approved''), (''Declined''), (''Processed'')')
END