USE [HR]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS(SELECT 1  FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Approval' AND COLUMN_NAME = 'ApproverAspNetUserId')
BEGIN
	ALTER TABLE Approval
	DROP COLUMN ApproverAspNetUserId
END

IF NOT EXISTS(SELECT 1 FROM information_schema.table_constraints WHERE constraint_type = 'Primary Key' AND TABLE_NAME = 'Approval')
BEGIN
	ALTER TABLE Approval
	Drop COLUMN ApprovalId

	ALTER TABLE Approval
	ADD ApprovalId INT IDENTITY(1,1) PRIMARY KEY
END

IF (EXISTS(SELECT 1  FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ApprovalEntityType' AND COLUMN_NAME = 'ApprovalEntityTypeId')
	AND EXISTS(SELECT 1  FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Approval' AND COLUMN_NAME = 'ApprovalEntityId'))
BEGIN
	EXEC sp_RENAME 'Approval.ApprovalEntityId' , 'ApprovalEntityTypeId', 'COLUMN'
END
