USE [HR]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS(SELECT 1  FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Overtime' AND COLUMN_NAME = 'Name')
BEGIN
	ALTER TABLE Overtime
	DROP COLUMN Name
	EXECUTE('UPDATE OvertimePreference SET Name = ''TOIL'' WHERE OvertimePreferenceId = 2')
END

IF EXISTS(SELECT 1  FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Overtime' AND COLUMN_NAME = 'OvertimeStateId')
BEGIN
	ALTER TABLE Overtime
	DROP CONSTRAINT DF_Overtime_OvertimeStateId
	
	ALTER TABLE Overtime
	DROP COLUMN OvertimeStateId
END

IF NOT EXISTS(SELECT 1  FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Overtime' AND COLUMN_NAME = 'ApprovalStateId')
BEGIN
	ALTER TABLE Overtime
	ADD ApprovalStateId INT NOT NULL
	
	ALTER TABLE Overtime
	ADD FOREIGN KEY (ApprovalStateId) REFERENCES ApprovalState(ApprovalStateId)
END
