USE [HR]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF (EXISTS(SELECT 1  FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ApprovalEntityType' AND COLUMN_NAME = 'ApprovalEntityTypeId')
	AND EXISTS(SELECT 1  FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PersonnelApprovalModel' AND COLUMN_NAME = 'ApprovalEntityId'))
BEGIN
	EXEC sp_RENAME 'PersonnelApprovalModel.ApprovalEntityId' , 'ApprovalEntityTypeId', 'COLUMN'
END
